apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: ecommerce-app-chaos
  namespace: ecommerce-app
spec:
  appinfo:
    appns: 'ecommerce-app'
    applabel: 'app=catalog-service'
    appkind: 'deployment'
  annotationCheck: 'true'
  engineState: 'active'
  auxiliaryAppInfo: ''
  chaosServiceAccount: chaos-experiment
  jobCleanUpPolicy: 'delete'
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '60'

            # set chaos interval (in sec) as desired
            - name: CHAOS_INTERVAL
              value: '3'

            # pod failures without '--force' & default terminationGracePeriodSeconds
            - name: FORCE
              value: 'false'