destinationServer: ''
argoNamespace: ''
argoProject: ''

spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/JJanetLi/chaos-eks-fis-aws
    targetRevision: main

  # Thoses default values can be surcharged by Infrastructure as Code
  clusterName: chaos-cluster # the name of EKS cluster
  blueprint: 'terraform' # cdk | terraform
