apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ecommerce-app-gateway
  namespace: ecommerce-app
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ecommerce-app
  namespace: ecommerce-app
spec:
  hosts:
  - "*"
  gateways:
  - ecommerce-app-gateway
  http:
  - match:
    - uri:
        prefix: /products
    route:
    - destination:
        host: catalog-service
        port:
          number: 80
  - match:
    - uri:
        prefix: /cart
    route:
    - destination:
        host: cart-service
        port:
          number: 80
  - match:
    - uri:
        prefix: /orders
    - uri:
        prefix: /checkout
    route:
    - destination:
        host: order-service
        port:
          number: 80